name: Compile latex
on: 
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository 
        uses: actions/checkout@v3
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.aux
          compiler: bibtex
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Commit file to build branch
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git fetch
          git checkout -b temp
          git reset origin/build
          git checkout build
          git branch -d temp
          git add -f main.pdf && git add -f --renormalize main.pdf
          git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
          NO_PAGER=1 git --no-pager diff HEAD^
          git push origin build
