name: test
on: [push]
jobs:
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: antaljanosbenjamin/compile-latex@v1.0.0
        with:
          file: main.tex
          args: -pdf
      - run: '(test -f main.pdf && echo PDF exists) || (echo PDF does not exist && exit 1)'
      - run: 'ls -alh'
      - uses: actions/checkout@v3
        with:
          ref: build
      - run: 'ls -alh'
      - name: Commit file
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add -f main.pdf && git add -f --renormalize main.pdf
          git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
          NO_PAGER=1 git --no-pager diff HEAD^
          git push
